[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[theme]
primaryColor = "#3b82f6"
backgroundColor = "#0e1726"
secondaryBackgroundColor = "#1e293b"
textColor = "#f8fafc"
font = "sans serif"
